name: 🐍 Pastel Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate lavender snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Adtkre
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#dd79d9
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#dd79d9

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          keep_history: false
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
